name: Publish

on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    # Clone repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      # Install Node.js
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/

      - name: Convert WebP
        run: |
          npx webp-batch-convert@0.1.2 --in img --out webp -q 75 -quiet
          mv webp/*.webp img/
          git config --global user.email "me@wol1.xyz"
          git config --global user.name "WoLeo-Z"
          git add . && git commit -m "Convert to WebP"

      # Publish to npm
      - name: Publish Package
        run: |
          npm version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Clean
        run: |
          rm -rf webp/*
          rm -rf img/*
          touch webp/.gitkeep
          touch img/.gitkeep

      - name: Push
        run: |
          git add -A
          git commit -m "Publish"
          git push origin master
