name: Publish

on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/

      - name: Convert WebP
        run: |
          npx webp-batch-convert@0.1.2 --in img --out img -q 80 -quiet
          git config --global user.email "me@w0l.top"
          git config --global user.name "WoLeo-Z"
          git add . && git commit -m "Convert to WebP"

      - name: Publish Package
        run: |
          npm version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Clean up
        run: |
          rm -rf img
          rm -rf files
          mkdir img && touch img/.gitkeep
          mkdir files && touch files/.gitkeep
          git add -A
          git commit -m "Publish"
          git push origin master
